### ISSUE TITLE
消息触发器相关说明有误

### ISSUE THREAD

**Issue by GWYOG** [pcrbot/hoshinobot-development-documentation#1]
[trigger.md](https://github.com/pcrbot/hoshinobot-development-documentation/blob/master/trigger.md)中关于触发优先级的描述有误。当触发器同优先级时HoshinoBot不是按导入包的顺序进行判断，而是选择最长的前缀触发关键词。无论`@sv.on_fullmatch('优先级测试')`与`@sv.on_prefix('优先级')`哪个在前，当输入`"优先级测试"`时触发的都是`on_fullmatch`，因为前缀关键词`'优先级测试'`的长度比前缀关键词`'优先级'`更长。

**Comment by var-mixer** [comment]
感谢大佬，已修改描述。
